# Generated by Django 4.2 on 2023-04-26 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pub_date',
            new_name='published_date',
        ),
    ]
